# cloudbuild.yaml  (for sc-pipeline)
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: services
  _BUCKET: rare-result-471319-e6-dataflow   # must be all lowercase and EXIST/BE CREATED
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/sc-pipeline:latest
  _TEMPLATE_PATH: gs://$_BUCKET/templates/sc-pipeline.json

steps:
# 0) Ensure the Dataflow bucket exists (idempotent)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -lc
    - |
      gsutil ls gs://$_BUCKET || gsutil mb -l $_REGION gs://$_BUCKET

# 1) Build and push pipeline image
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','$_IMAGE','.']

- name: gcr.io/cloud-builders/docker
  args: ['push','$_IMAGE']

# 2) Build the Flex Template spec in GCS
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    [
      'dataflow','flex-template','build','$_TEMPLATE_PATH',
      '--image','$_IMAGE',
      '--sdk-language','PYTHON',
      '--metadata-file','metadata.json'
    ]
