options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: services
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/sc-pipeline:latest
  _TEMPLATE_PATH: gs://$PROJECT_ID-dataflow/templates/sc-pipeline.json

steps:
# Ensure the template bucket exists (no-op if already exists)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      gcloud storage buckets create gs://$PROJECT_ID-dataflow --location=${_REGION} || true
      gcloud storage buckets create gs://$PROJECT_ID-dataflow/tmp --location=${_REGION} || true

# Build & push the pipeline image
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','$_IMAGE','.']

- name: gcr.io/cloud-builders/docker
  args: ['push','$_IMAGE']

# Build the Flex Template spec JSON in GCS
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      'dataflow','flex-template','build','$_TEMPLATE_PATH',
      '--image','$_IMAGE',
      '--sdk-language','PYTHON',
      '--metadata-file','metadata.json'
    ]

