options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: services
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/sc-pipeline:latest
  _TEMPLATE_PATH: gs://$PROJECT_ID-dataflow/templates/sc-pipeline.json

steps:
# Build and push pipeline image
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','$_IMAGE','.']

- name: gcr.io/cloud-builders/docker
  args: ['push','$_IMAGE']

# Build Flex Template spec into GCS
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      'dataflow','flex-template','build','$_TEMPLATE_PATH',
      '--image','$_IMAGE',
      '--sdk-language','PYTHON',
      '--metadata-file','metadata.json'
    ]

# (optional) set Artifact Registry reader for DF worker SA
